---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: validate
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/terraform-toolset:v1.1.3-2
  commands:
  - mv __providers__._tf_ providers.tf
  - /acp/scripts/tf-validate.sh
  - mv providers.tf __providers__._tf_
  when:
    event:
    - pull_request
    - push

...